services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb_data

  bot:
    build: .
    container_name: telegram-bot
    command: node services/bot/index.js
    restart: unless-stopped
    depends_on:
      - pocketbase
    env_file:
      - .env
    environment:
      - TELEGRAM_WHITELIST_IDS=${TELEGRAM_USER_ID}
      - POCKETBASE_URL=http://pocketbase:8090

volumes:
  pb_data:
